server:
  port: 1234

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/skillssystem"
    username: root
    password: Dat160204
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "Mt9ot83HH0WQPSxFfFN1tMRSYaPe7mFbq5mqZEMVgpubEZo6TjRNeXseLlLxUbhM"